import UInput from '../UInput.js';
import Device from './Device.js';

/* @typedef {import('./Device.js').IEvent} IEvent */

const T = UInput.Event.TYPES;
const { KEY } = UInput.Event.EVENTS;

/**
 * @enum {IEvent}
 */
const EVENTS = {
	KEY_HELP:
		[T.KEY, KEY.KEY_HELP],

	KEY_SLEEP :
		[T.KEY, KEY.KEY_SLEEP],
	KEY_WAKEUP:
		[T.KEY, KEY.KEY_WAKEUP],
	KEY_SCREENLOCK:
		[T.KEY, KEY.KEY_SCREENLOCK],

	KEY_BOOKMARKS:
		[T.KEY, KEY.KEY_BOOKMARKS],
	KEY_COMPUTER:
		[T.KEY, KEY.KEY_COMPUTER],
	KEY_FILE:
		[T.KEY, KEY.KEY_FILE],
	KEY_CONFIG:
		[T.KEY, KEY.KEY_CONFIG],


	KEY_PROG1:
		[T.KEY, KEY.KEY_PROG1],
	KEY_PROG2:
		[T.KEY, KEY.KEY_PROG2],
	KEY_CALC:
		[T.KEY, KEY.KEY_CALC],
	KEY_WWW:
		[T.KEY, KEY.KEY_WWW],
	KEY_MEDIA:
		[T.KEY, KEY.KEY_MEDIA],
	KEY_AUDIO:
		[T.KEY, KEY.KEY_AUDIO],
	KEY_VIDEO:
		[T.KEY, KEY.KEY_VIDEO],
	KEY_MAIL:
		[T.KEY, KEY.KEY_MAIL],
	KEY_PHONE:
		[T.KEY, KEY.KEY_PHONE],
	KEY_CAMERA:
		[T.KEY, KEY.KEY_CAMERA],
	KEY_QUESTION :
		[T.KEY, KEY.KEY_QUESTION],
	KEY_CHAT:
		[T.KEY, KEY.KEY_CHAT],
	KEY_SEARCH:
		[T.KEY, KEY.KEY_SEARCH],
	KEY_FINANCE:
		[T.KEY, KEY.KEY_FINANCE],
	KEY_SPORT:
		[T.KEY, KEY.KEY_SPORT],
	KEY_SHOP:
		[T.KEY, KEY.KEY_SHOP],

	KEY_PLAYPAUSE:
		[T.KEY, KEY.KEY_PLAYPAUSE],
	KEY_PLAY:
		[T.KEY, KEY.KEY_PLAY],
	KEY_PAUSE:
		[T.KEY, KEY.KEY_PAUSE],
	KEY_STOP:
		[T.KEY, KEY.KEY_STOP],
	KEY_NEXTSONG:
		[T.KEY, KEY.KEY_NEXTSONG],
	KEY_PREVIOUSSONG:
		[T.KEY, KEY.KEY_PREVIOUSSONG],
	KEY_FASTFORWARD:
		[T.KEY, KEY.KEY_FASTFORWARD],
	KEY_REWIND:
		[T.KEY, KEY.KEY_REWIND],
	KEY_RECORD:
		[T.KEY, KEY.KEY_RECORD],

	KEY_MUTE:
		[T.KEY, KEY.KEY_MUTE],
	KEY_VOLUMEUP:
		[T.KEY, KEY.KEY_VOLUMEUP],
	KEY_VOLUMEDOWN:
		[T.KEY, KEY.KEY_VOLUMEDOWN],
	KEY_MICMUTE:
		[T.KEY, KEY.KEY_MICMUTE],

	KEY_BRIGHTNESSDOWN:
		[T.KEY, KEY.KEY_BRIGHTNESSDOWN],
	KEY_BRIGHTNESSUP:
		[T.KEY, KEY.KEY_BRIGHTNESSUP],

}

class Media extends Device {
	constructor(name = 'node-virtual-media-keys') {
		super(EVENTS, name);
	}

	static EVENTS = EVENTS;
}

export default Media;

